import { ArrowUpRight, Quote } from "lucide-react";
import { FOUNDERS, PRINCIPLES, WHO_FOR_CARDS } from "@/data/aboutData";
import { Eyebrow, HotelImage, SectionHeading, TextLink } from "./Primitives";

export default function AboutPage() {
  return <>
    <section className="ib-dark ib-about-hero"><div className="ib-container"><Eyebrow>WHY INNBASE EXISTS</Eyebrow><h1>Hospitality is personal.<br /><em>The work should feel that way.</em></h1><div className="ib-about-intro"><p>We’re building for the people who keep the lights on, the guests comfortable, and the business moving.</p><TextLink href="#story">Here’s where we started</TextLink></div></div></section>
    <section className="ib-section ib-story" id="story"><div className="ib-container ib-story-layout"><div className="ib-story-image"><HotelImage priority /><span>A GREAT STAY HAS A LOT GOING ON BEHIND IT.</span></div><div className="ib-story-copy"><Eyebrow>THE PROBLEM WE COULDN’T IGNORE</Eyebrow><h2>“What happened<br /><em>last night?”</em></h2><p className="ib-large-copy">Three people. Three answers. Each one holding a different piece of the same story.</p><p>A hotel generates information with every booking, every meal, every payment, and every shift. Too often, that information ends up scattered across notebooks, spreadsheets, and conversations.</p><p>Innbase brings the records together. So an owner can understand the business, a manager can explain a variance, and a team can hand over without starting from scratch.</p><div className="ib-story-signoff"><span />That’s the work we believe is worth doing.</div></div></div></section>
    <section className="ib-section ib-paper-alt" id="reality"><div className="ib-container"><SectionHeading eyebrow="BUILT IN NIGERIA. BUILT FOR REALITY." title={<>The phone rings.<br />The guest pays cash.<br /><em>The system should keep up.</em></>}><p>We’re designing around the way hospitality actually works here: phone bookings, transfers, cash payments, busy handovers, and owners checking in from home.</p></SectionHeading><div className="ib-reality-list">{WHO_FOR_CARDS.map((item, i) => <article key={item.title}><span>0{i + 1}</span><h3>{item.title}</h3><p><b>{item.pain}</b>{item.fix}</p></article>)}</div></div></section>
    <section className="ib-section ib-dark" id="principles"><div className="ib-container ib-principles-layout"><div><Eyebrow>WHAT WE COME BACK TO</Eyebrow><h2>A few things<br /><em>we won’t lose sight of.</em></h2><p>Useful software starts with respect for the people using it.</p></div><div>{PRINCIPLES.map((item, i) => <article key={item.title}><span>0{i + 1}</span><div><h3>{item.title}</h3><p>{item.body}</p></div></article>)}</div></div></section>
    <section className="ib-section" id="team"><div className="ib-container"><SectionHeading eyebrow="THE PEOPLE BUILDING IT" title={<>Two founders.<br /><em>One shared conviction.</em></>}><p>A system should help you understand your business. Its complexity should never become your team’s problem.</p></SectionHeading><div className="ib-founders">{FOUNDERS.map((founder, i) => <article key={founder.name}><div className="ib-founder-top"><span>0{i + 1} / CO-FOUNDER</span><span>{founder.role}</span></div><h3>{founder.name}</h3><blockquote><Quote size={23} strokeWidth={1.4} aria-hidden="true" /><p>“{founder.quote}”</p></blockquote><p className="ib-founder-focus"><b>Focus</b>{founder.focus}</p><div className="ib-founder-links"><a href={founder.linkedin} target="_blank" rel="noopener noreferrer">LinkedIn<ArrowUpRight size={15} aria-hidden="true" /></a><a href={founder.twitter} target="_blank" rel="noopener noreferrer">X<ArrowUpRight size={15} aria-hidden="true" /></a></div></article>)}</div></div></section>
    <section className="ib-letter-section" id="letter"><div className="ib-container ib-letter-layout"><div><Eyebrow>A NOTE FROM US</Eyebrow><h2>Before<br /><em>you go.</em></h2></div><div className="ib-letter"><p className="ib-letter-salute">To every hotel owner trying to keep it all together,</p><p>We know the feeling of asking “what happened last night?” and getting three different answers from three different people — none of them wrong, exactly, just incomplete.</p><p>We’re not here to add another system for your staff to fight with during a busy shift. We’re here because we think that feeling is solvable, and worth solving properly, not with a quick patch.</p><p>That means slower, more careful work than a flashy launch would suggest. We’re building this for the long term, one hotel at a time, and we’d rather earn your trust than ask for it upfront.</p><div className="ib-letter-signature">Efe &amp; Chibeze<span>Founders, Innbase</span></div></div></div></section>
  </>;
}
