import { ArrowDown, Check, MessageSquare, Sparkles, FileText, Smartphone, Monitor, Mic } from "lucide-react";
import { OA_FAQ, OA_ROLE_CARDS } from "@/data/operationalAssistantData";
import { Button, Eyebrow, FAQ, ProductBridge, Reassurance, SectionHeading } from "./Primitives";
import AssistantDemo from "./AssistantDemo";

export default function AssistantPage() {
  return <>
    <section className="ib-dark"><div className="ib-container ib-split-hero ib-assistant-hero"><div className="ib-hero-copy"><Eyebrow>AI OPERATIONAL ASSISTANT</Eyebrow><h1>Less chasing.<br />More <em>taking care.</em></h1><p>Ask a question. Log an issue. Find out what needs attention. Give your team a simpler way to work with Innbase, in their own words.</p><div className="ib-actions"><Button href="#demo">Try a day with the assistant</Button></div><Reassurance>Included on every Innbase plan.</Reassurance></div><div className="ib-assistant-hero-scene"><span className="ib-assistant-orbit" aria-hidden="true" /><div className="ib-question-slip"><MessageSquare size={21} aria-hidden="true" /><p>“The guest in 105 says<br />the AC isn’t cooling.”</p><span>FRONT DESK / EXAMPLE</span></div><div className="ib-action-slip"><div><Sparkles size={22} aria-hidden="true" /><span>FROM WORDS TO WORK</span></div><h2>Got it.<br /><em>Let’s take care of it.</em></h2><div className="ib-slip-record"><FileText size={20} aria-hidden="true" /><p><b>Room 105 · Maintenance</b><span>Air conditioner not cooling</span></p><Check size={18} aria-hidden="true" /></div><p className="ib-slip-note">Illustrative response · connected to an operational record</p><a href="#demo">Explore the conversation <ArrowDown size={16} aria-hidden="true" /></a></div></div></div></section>
    <section className="ib-section" id="demo"><div className="ib-container"><SectionHeading eyebrow="A DAY IN THE LIFE" title={<>From the morning briefing<br /><em>to the last handover.</em></>}><p>Follow the team through five moments in a hotel day. Choose a request, send it, and explore the example record behind the answer.</p></SectionHeading><AssistantDemo /></div></section>
    <section className="ib-section ib-paper-alt" id="rules"><div className="ib-container ib-assistant-rules"><div><Eyebrow>HELPFUL, WITH BOUNDARIES</Eyebrow><h2>A capable assistant.<br /><em>Your team in charge.</em></h2><p>It works inside Innbase’s permissions and records. Your staff ask; the assistant helps them understand or act.</p></div><ol className="ib-numbered-list">{[["Starts with your team", "Staff initiate the conversation. The assistant responds to what they ask it to do."], ["Respects the role", "A front-desk request cannot become a manager-level action. Existing permissions still apply."], ["Keeps the record", "Actions are logged in Innbase. When a request is unclear, the assistant asks before proceeding."]].map(([title, body], i) => <li key={title}><span>0{i + 1}</span><div><h3>{title}</h3><p>{body}</p></div></li>)}</ol></div></section>
    <section className="ib-section" id="team"><div className="ib-container"><SectionHeading eyebrow="WHEREVER THE WORK HAPPENS" title={<>From the front desk.<br /><em>Or the next floor up.</em></>}><p>Use the assistant on a phone or desktop. Voice is coming soon.</p></SectionHeading><div className="ib-assistant-role-grid">{OA_ROLE_CARDS.map((role, i) => <article key={role.title}><span>0{i + 1}</span><h3>{role.title}</h3><p>{role.fix}</p></article>)}</div><div className="ib-device-strip"><span><Smartphone size={21} aria-hidden="true" />Phone</span><span><Monitor size={21} aria-hidden="true" />Desktop</span><span><Mic size={21} aria-hidden="true" />Voice <small>Coming soon</small></span></div></div></section><ProductBridge /><FAQ items={OA_FAQ} />
  </>;
}
