"use client";

import { useState } from "react";
import Link from "next/link";
import { Check, Users, Building2, Smartphone, ArrowUpRight } from "lucide-react";
import { PLANS, COMPARE_ROWS, CONTRAST_ACTUAL } from "@/data/pricingPlans";
import { PRICING_FAQS } from "@/data/pricingFaqData";
import { Button, Eyebrow, FAQ, HotelImage, Reassurance, SectionHeading, TextLink } from "./Primitives";

const CAPACITIES = [10, 20, 50];
const BANDS = ["1–10", "11–20", "21–50", "51+"];

export default function PricingPage() {
  const [band, setBand] = useState(0);
  const [differences, setDifferences] = useState(false);
  const rows = COMPARE_ROWS.filter(row => differences ? row.feature && !row.same : true);
  const chosen = PLANS[band];
  return <>
    <section className="ib-dark ib-pricing-hero"><div className="ib-container ib-pricing-intro"><div><Eyebrow>INNBASE PRICING</Eyebrow><h1>A plan that fits.<br /><em>Room to grow.</em></h1></div><div><p>One flat monthly price, in Naira.<br />The core tools to run your hotel, included in every plan.</p><div className="ib-inline-assurances"><Reassurance>1-month free trial</Reassurance><Reassurance>No card to start</Reassurance></div></div></div></section>
    <section className="ib-plans-section" id="plans"><div className="ib-container"><div className="ib-plan-picker"><div><h2>Find your team’s fit.</h2><p>How many people need workspace access?</p></div><fieldset><legend className="ib-sr-only">Number of staff accounts</legend>{BANDS.map((label, i) => <label key={label}><input type="radio" name="team-size" value={i} checked={band === i} onChange={() => setBand(i)} /><span>{label}<small>people</small></span></label>)}</fieldset><p className="ib-picker-result" role="status" aria-live="polite" aria-atomic="true"><strong>{chosen?.name || "Enterprise"}</strong>{chosen ? ` covers your team size. Up to ${CAPACITIES[band]} staff accounts.` : " is the next step for more than 50 staff accounts."}</p></div>
      <div className="ib-plan-grid">{PLANS.map((plan, i) => <article className={`ib-plan-card ${i === 2 ? "ib-growth-card" : ""} ${i === band ? "is-recommended" : ""}`} key={plan.name} id={`plan-${plan.name.toLowerCase()}`}><div className="ib-plan-card-head"><h3>{plan.name}</h3>{band === i ? <span className="ib-fit-badge">YOUR TEAM SIZE</span> : i === 2 ? <span className="ib-plan-tag">GO GUEST-FACING</span> : null}</div><p className="ib-plan-description">{plan.tagline}</p><p className="ib-plan-capacity"><Users size={16} aria-hidden="true" />Up to <strong>{CAPACITIES[i]} staff accounts</strong></p><p className="ib-price"><span>₦</span>{plan.price.slice(1)}<small>/month</small></p><p className="ib-daily">{plan.daily}</p><Button href={`/contact?plan=${plan.name.toLowerCase()}`} variant={i === band ? "dark" : "outline"}>Start with {plan.name}</Button><div className="ib-plan-features"><span>{["YOUR CORE OPERATION, CONNECTED", "MORE ROOM FOR YOUR TEAM", "YOUR TEAM. AND YOUR GUESTS."][i]}</span><ul>{plan.features.map(feature => <li key={feature}><Check size={16} aria-hidden="true" /><span>{feature.includes("Guest Companion") ? <Link href="/guest-companion">{feature}<ArrowUpRight size={13} aria-hidden="true" /></Link> : feature}</span></li>)}</ul></div></article>)}</div>
      <div className="ib-pricing-clarity"><p><strong>One price for your team’s capacity.</strong> No separate charge for each staff account within your plan.</p><small>Daily equivalents use a 30-day month. Billing is monthly.</small></div><article className={`ib-enterprise ${band === 3 ? "is-recommended" : ""}`} id="plan-enterprise"><Building2 size={36} strokeWidth={1.3} aria-hidden="true" /><div><h3>A bigger operation? {band === 3 && <span className="ib-fit-badge">YOUR TEAM SIZE</span>}</h3><p>For more than 50 staff accounts or multiple properties, let’s shape an Enterprise plan around you.</p></div><TextLink href="/contact?plan=enterprise">Talk about Enterprise</TextLink></article><p className="ib-growth-note"><Smartphone size={17} aria-hidden="true" />Want Guest Companion? Choose Growth at any team size within its 50-account capacity.</p>
    </div></section>
    <section className="ib-section ib-paper-alt" id="compare"><div className="ib-container"><SectionHeading eyebrow="THE DETAILS, IN PLAIN SIGHT" title={<>Know what<br /><em>comes with it.</em></>}><p>The core operation is included in every plan. Here’s where capacity and guest tools differ.</p><label className="ib-difference-switch"><input type="checkbox" role="switch" checked={differences} onChange={e => setDifferences(e.target.checked)} aria-controls="ib-comparison-body" /><span aria-hidden="true" />Show differences only</label></SectionHeading><div className="ib-comparison-scroll" role="region" aria-label="Plan comparison; scroll horizontally on smaller screens" tabIndex={0}><table className="ib-comparison"><caption className="ib-sr-only">Monthly Innbase plans. Enterprise is quoted separately.</caption><thead><tr><th scope="col">One operating system.<br />Three ways to grow.</th>{PLANS.map(plan => <th scope="col" key={plan.name}>{plan.name}<span>{plan.price} / month</span></th>)}</tr></thead><tbody id="ib-comparison-body"><tr><th scope="row">Staff accounts</th>{CAPACITIES.map(cap => <td key={cap}>Up to <strong>{cap}</strong></td>)}</tr>{rows.map((row, i) => row.section ? <tr className="ib-comparison-category" key={row.section}><th colSpan={4} scope="colgroup">{row.section}</th></tr> : <tr key={row.feature || i}><th scope="row">{row.feature}</th>{row.values.map((value, j) => <td key={j}>{value === true ? <span className="ib-included"><Check size={15} aria-hidden="true" /><span>Included</span></span> : value === false ? <span className="ib-unavailable">Not included</span> : value}</td>)}</tr>)}</tbody></table></div><p className="ib-comparison-status" role="status">Showing {1 + rows.filter(row => row.feature).length} {differences ? "plan differences" : "comparison rows"}.</p></div></section>
    <section className="ib-section ib-dark" id="capacity"><div className="ib-container ib-capacity-layout"><div><Eyebrow>MORE HOSPITALITY. LESS METER-WATCHING.</Eyebrow><h2>Your team has<br /><em>enough to think about.</em></h2><p>The AI Operational Assistant is included on every plan. If your operation needs more capacity, we start with a conversation. No surprise AI overage invoice.</p><ul className="ib-check-list">{CONTRAST_ACTUAL.map(item => <li key={item}><Check size={17} aria-hidden="true" />{item}</li>)}</ul><TextLink href="/legal#fair-usage">Read our fair usage policy</TextLink></div><div className="ib-capacity-photo"><HotelImage /><div><span>SPACE TO FOCUS ON WHAT MATTERS</span><h3>Take care of your guests.<br /><em>We’ll talk when you grow.</em></h3></div></div></div></section>
    <FAQ items={PRICING_FAQS} title={<>Straight answers.<br /><em>Before you decide.</em></>} />
  </>;
}
