export const AREAS = ['Rooms','Kitchen','Laundry','Generator','Common Areas'];
export const AREA_ICON = {'Rooms':'bed-double','Kitchen':'cooking-pot','Laundry':'shirt','Generator':'fuel','Common Areas':'building-2'};
export const CATEGORY_ICON = {'AC':'wind','Water Heater':'droplet','Freezer':'snowflake','Door':'door-open','Plumbing':'droplet','Electrical':'zap','Generator Service':'fuel','Washing Machine':'shirt','Structural':'hammer','Other':'wrench'};

/* The truth of a repair isn't "Pending" — it's one of these. Order = the real lifecycle. */
export const STATUS_ORDER = ['reported','quote','waiting','onsite','inprogress','parts','inspection','completed'];
export const STATUS_META = {
    reported:   {label:'Reported',              short:'Reported',      icon:'alert-circle',     color:'red'},
    quote:      {label:'Waiting for Quotation',  short:'Quotation',     icon:'file-text',        color:'amber'},
    waiting:    {label:'Waiting for Artisan',    short:'Artisan',       icon:'phone-call',       color:'orange'},
    onsite:     {label:'Artisan On-Site',        short:'On-Site',       icon:'hard-hat',         color:'blue'},
    inprogress: {label:'Repair in Progress',     short:'In Progress',   icon:'hammer',           color:'tealfill'},
    parts:      {label:'Waiting for Parts',      short:'Parts',        icon:'package',          color:'purple'},
    inspection: {label:'Ready for Inspection',   short:'Inspection',   icon:'clipboard-check',  color:'teal'},
    completed:  {label:'Completed',              short:'Completed',    icon:'check-circle-2',   color:'green'},
};
export const STATUS_COLOR = {
    red:{text:'var(--danger)', bg:'var(--danger-soft)'},
    amber:{text:'var(--warning-text)', bg:'var(--warning-soft)'},
    orange:{text:'var(--accent-warm)', bg:'var(--color-warning-soft)'},
    blue:{text:'var(--info)', bg:'var(--info-soft)'},
    tealfill:{text:'var(--accent-strong)', bg:'var(--color-accent-soft)'},
    purple:{text:'var(--ai-text)', bg:'var(--ai-soft)'},
    teal:{text:'var(--accent)', bg:'var(--color-accent-soft)'},
    green:{text:'var(--success-text)', bg:'var(--success-soft)'},
};
function commIcon(type: string) { return type==='call' ? 'phone-call' : type==='whatsapp' ? 'message-circle' : 'mail'; }

/* ═══════════════════ VENDORS — history, not just a name ═══════════════════ */
export const VENDORS = {
    kunle:   {name:'Kunle AC Repairs',        jobs:31, completionRate:94, avgResponseDays:1.2, lastVisit:'2 days ago',
        recentJobs:[{room:'Room 105',what:'AC not cooling',when:'Today'},{room:'Lobby',what:'AC dripping water',when:'Today'},{room:'Room 210',what:'AC gas top-up',when:'5 weeks ago'}]},
    tunde:   {name:'Tunde Plumbing Works',    jobs:19, completionRate:97, avgResponseDays:0.8, lastVisit:'Yesterday',
        recentJobs:[{room:'Room 212',what:'Water heater not heating',when:'Yesterday'},{room:'Room 118',what:'Blocked drain',when:'3 weeks ago'}]},
    chukwu:  {name:'Chukwu Electricals',      jobs:12, completionRate:100, avgResponseDays:1.5, lastVisit:'Yesterday',
        recentJobs:[{room:'Laundry Room',what:'Washing machine drum',when:'Yesterday'},{room:'Room 401',what:'Socket outlet sparked',when:'2 days ago'}]},
    cooltech:{name:'CoolTech Refrigeration',  jobs:6,  completionRate:83,  avgResponseDays:2.1, lastVisit:'3 weeks ago',
        recentJobs:[{room:'Kitchen',what:'Walk-in freezer running warm',when:'Today'},{room:'Kitchen',what:'Freezer thermostat',when:'4 months ago'}]},
    emeka:   {name:'Emeka Generator Services',jobs:9,  completionRate:89,  avgResponseDays:0.6, lastVisit:'Today',
        recentJobs:[{room:'Generator House',what:'Smoking on startup',when:'Today'},{room:'Generator House',what:'Oil change overdue',when:'2 months ago'}]},
    bright:  {name:'Bright Locksmiths',       jobs:14, completionRate:100, avgResponseDays:0.4, lastVisit:'Today',
        recentJobs:[{room:'Room 308',what:'Door lock jammed',when:'Today'},{room:'Room 220',what:'Key card reader',when:'6 weeks ago'}]},
};

/* ═══════════════════ ISSUES ═══════════════════ */
let IID = 1;
export const ISSUES = [
    { id:IID++, room:'Room 105', area:'Rooms', category:'AC', title:'AC not cooling', priority:'high', status:'waiting',
        reportedBy:'Front Desk', reportedRel:'8 mins ago', reportedAt:'Today, 8:44 AM', roomBlocked:true, blockDecided:true,
        vendorKey:'kunle', preferred:'Phone Call', etaText:'Pending confirmation',
        commLog:[{type:'call', note:'Supervisor called Kunle — no answer', time:'8:52 AM'}],
        cost:{estimate:18000, approved:null, actual:null, payment:null},
        lineItems:[{label:'Gas refill', amount:12000},{label:'Callout / transport', amount:6000}],
        costHistory:[{when:'6 weeks ago', amount:9000, note:'Compressor noise — serviced'},{when:'5 months ago', amount:7500, note:'Gas top-up'}],
        timeline:[
            {icon:'alert-circle', label:'Guest reports AC not cooling', time:'8:44 AM'},
            {icon:'file-text', label:'Issue logged', time:'8:46 AM'},
            {icon:'user-check', label:'Supervisor notified', time:'8:48 AM'},
            {icon:'phone-call', label:'Called Kunle AC — no answer', time:'8:52 AM'},
        ],
        attachments:[{type:'photo', name:'ac_unit.jpg'}],
        repeatHistory:[{label:'AC — compressor noise', when:'6 weeks ago'},{label:'AC — not cooling', when:'3 months ago'},{label:'AC — gas top-up', when:'5 months ago'}],
        asset:{name:'LG Split AC 1.5HP', installed:'2022', warranty:'Expired', estReplacement:165000},
        cleaningAsked:false, needsCleaning:null },

    { id:IID++, room:'Room 212', area:'Rooms', category:'Water Heater', title:'Water heater not heating', priority:'medium', status:'onsite',
        reportedBy:'Housekeeping', reportedRel:'Yesterday', reportedAt:'Yesterday, 4:10 PM', roomBlocked:true, blockDecided:true,
        vendorKey:'tunde', preferred:'WhatsApp', etaText:'Today, by 10:00 AM',
        commLog:[{type:'call', note:'Called Tunde — coming tomorrow 8AM', time:'4:20 PM'},{type:'whatsapp', note:'Sent a photo of the unit', time:'4:24 PM'},{type:'call', note:'Arrived on site, diagnosing', time:'8:05 AM'}],
        cost:{estimate:12000, approved:true, actual:null, payment:null},
        lineItems:[{label:'Heating element', amount:8500},{label:'Callout / transport', amount:3500}],
        costHistory:[],
        timeline:[
            {icon:'alert-circle', label:'Housekeeping reports no hot water', time:'4:10 PM'},
            {icon:'file-text', label:'Issue logged', time:'4:12 PM'},
            {icon:'phone-call', label:'Called Tunde Plumbing Works', time:'4:20 PM'},
            {icon:'clock', label:'Artisan promised visit tomorrow, 8:00 AM', time:'4:21 PM'},
            {icon:'hard-hat', label:'Tunde arrived on site', time:'8:05 AM'},
        ],
        attachments:[{type:'photo', name:'heater_unit.jpg'}],
        repeatHistory:[], asset:{name:'Ariston 30L Heater', installed:'2021', warranty:'Expired', estReplacement:95000},
        cleaningAsked:false, needsCleaning:null },

    { id:IID++, room:'Kitchen', area:'Kitchen', category:'Freezer', title:'Walk-in freezer running warm', priority:'high', status:'reported',
        reportedBy:'Chef Ade', reportedRel:'2 hrs ago', reportedAt:'Today, 7:00 AM', roomBlocked:null, blockDecided:true,
        vendorKey:'cooltech', preferred:'Phone Call', etaText:'Not yet confirmed',
        commLog:[{type:'call', note:'Called CoolTech — no answer', time:'7:10 AM'}],
        cost:{estimate:45000, approved:false, actual:null, payment:null},
        lineItems:[{label:'Compressor diagnosis', amount:15000},{label:'Refrigerant gas', amount:22000},{label:'Callout / transport', amount:8000}],
        costHistory:[{when:'4 months ago', amount:14000, note:'Thermostat replaced'}],
        timeline:[
            {icon:'alert-circle', label:'Chef reports freezer running warm', time:'7:00 AM'},
            {icon:'file-text', label:'Issue logged', time:'7:02 AM'},
            {icon:'phone-call', label:'Called CoolTech Refrigeration — no answer', time:'7:10 AM'},
        ],
        attachments:[], repeatHistory:[{label:'Freezer — thermostat', when:'4 months ago'}],
        asset:{name:'Haier Walk-in Freezer', installed:'2019', warranty:'Expired', estReplacement:480000},
        cleaningAsked:false, needsCleaning:null },

    { id:IID++, room:'Room 308', area:'Rooms', category:'Door', title:'Door lock repaired', priority:'low', status:'completed',
        reportedBy:'Front Desk', reportedRel:'Completed today', reportedAt:'Today, 10:20 AM', roomBlocked:false, blockDecided:true,
        vendorKey:'bright', preferred:'Phone Call', etaText:'Complete',
        commLog:[{type:'call', note:'Called Bright — arrived within the hour', time:'9:10 AM'}],
        cost:{estimate:6000, approved:true, actual:6000, payment:'Cash'},
        lineItems:[{label:'Lock mechanism', amount:4500},{label:'Callout / transport', amount:1500}],
        costHistory:[{when:'6 weeks ago', amount:3000, note:'Key card reader — Room 220 (same vendor)'}],
        timeline:[
            {icon:'alert-circle', label:'Guest reports door lock jammed', time:'8:50 AM'},
            {icon:'file-text', label:'Issue logged', time:'8:52 AM'},
            {icon:'phone-call', label:'Called Bright Locksmiths', time:'9:10 AM'},
            {icon:'hammer', label:'Locksmith arrived, lock mechanism replaced', time:'9:55 AM'},
            {icon:'check-circle-2', label:'Room returned to service', time:'10:20 AM'},
        ],
        attachments:[{type:'receipt', name:'receipt_308.jpg'}], repeatHistory:[],
        asset:{name:'Standard Door Lock', installed:'2020', warranty:'Expired', estReplacement:22000},
        cleaningAsked:true, needsCleaning:false },

    { id:IID++, room:'Generator House', area:'Generator', category:'Generator Service', title:'Generator smoking on startup', priority:'high', status:'inprogress',
        reportedBy:'Maintenance', reportedRel:'3 hrs ago', reportedAt:'Today, 6:15 AM', roomBlocked:false, blockDecided:true,
        vendorKey:'emeka', preferred:'Phone Call', etaText:'Today, by 1:00 PM',
        commLog:[{type:'call', note:'Called Emeka — on site now', time:'6:40 AM'}],
        cost:{estimate:35000, approved:true, actual:null, payment:null},
        lineItems:[{label:'Fuel injector', amount:24000},{label:'Labor', amount:8000},{label:'Callout / transport', amount:3000}],
        costHistory:[{when:'2 months ago', amount:18000, note:'Overdue oil change serviced'}],
        timeline:[
            {icon:'alert-circle', label:'Duty engineer reports smoke on startup', time:'6:15 AM'},
            {icon:'file-text', label:'Issue logged', time:'6:18 AM'},
            {icon:'phone-call', label:'Called Emeka Generator Services', time:'6:40 AM'},
            {icon:'hard-hat', label:'Technician on site, diagnosing fuel injector', time:'7:20 AM'},
        ],
        attachments:[{type:'video', name:'startup_smoke.mp4'}], repeatHistory:[{label:'Generator — oil change overdue', when:'2 months ago'}],
        asset:{name:'Mikano 60KVA Generator', installed:'2020', warranty:'Expired', estReplacement:3200000},
        cleaningAsked:false, needsCleaning:null, propertyWide:true },

    { id:IID++, room:'Laundry Room', area:'Laundry', category:'Washing Machine', title:'Washing machine drum not spinning', priority:'medium', status:'quote',
        reportedBy:'Laundry Staff', reportedRel:'Yesterday', reportedAt:'Yesterday, 1:30 PM', roomBlocked:false, blockDecided:true,
        vendorKey:'chukwu', preferred:'Phone Call', etaText:'Awaiting quotation',
        commLog:[{type:'call', note:'Called Chukwu — will send quotation by Thursday', time:'1:45 PM'}],
        cost:{estimate:15000, approved:null, actual:null, payment:null},
        lineItems:[{label:'Drive belt (estimate)', amount:9000},{label:'Callout / transport', amount:6000}],
        costHistory:[],
        timeline:[
            {icon:'alert-circle', label:'Laundry staff reports drum not spinning', time:'1:30 PM'},
            {icon:'file-text', label:'Issue logged', time:'1:32 PM'},
            {icon:'phone-call', label:'Called Chukwu Electricals', time:'1:45 PM'},
            {icon:'file-text', label:'Quotation requested', time:'1:46 PM'},
        ],
        attachments:[], repeatHistory:[], asset:{name:'LG 15kg Commercial Washer', installed:'2022', warranty:'Active', estReplacement:850000},
        cleaningAsked:false, needsCleaning:null },

    { id:IID++, room:'Lobby', area:'Common Areas', category:'AC', title:'Lobby AC unit dripping water', priority:'low', status:'inspection',
        reportedBy:'Front Desk', reportedRel:'Today', reportedAt:'Today, 9:05 AM', roomBlocked:false, blockDecided:true,
        vendorKey:'kunle', preferred:'Phone Call', etaText:'Awaiting sign-off',
        commLog:[{type:'call', note:'Called Kunle — will check after Room 105 job', time:'9:12 AM'},{type:'call', note:'Drain line cleared, unit dry', time:'11:40 AM'}],
        cost:{estimate:5000, approved:true, actual:5000, payment:null},
        lineItems:[{label:'Drain line clearance', amount:5000}],
        costHistory:[],
        timeline:[
            {icon:'alert-circle', label:'Front desk reports water dripping from lobby AC', time:'9:05 AM'},
            {icon:'file-text', label:'Issue logged', time:'9:07 AM'},
            {icon:'phone-call', label:'Called Kunle AC Repairs', time:'9:12 AM'},
            {icon:'hammer', label:'Drain line cleared', time:'11:40 AM'},
            {icon:'clipboard-check', label:'Marked ready for inspection', time:'11:42 AM'},
        ],
        attachments:[{type:'photo', name:'lobby_drip.jpg'}], repeatHistory:[],
        asset:{name:'Split AC — Lobby', installed:'2021', warranty:'Expired', estReplacement:165000},
        cleaningAsked:false, needsCleaning:null },

    { id:IID++, room:'Room 401', area:'Rooms', category:'Electrical', title:'Socket outlet sparked, replaced', priority:'high', status:'completed',
        reportedBy:'Guest', reportedRel:'Yesterday', reportedAt:'Yesterday, 6:40 PM', roomBlocked:false, blockDecided:true,
        vendorKey:'chukwu', preferred:'Phone Call', etaText:'Complete',
        commLog:[{type:'call', note:'Called Chukwu — arrived same evening', time:'6:55 PM'}],
        cost:{estimate:8000, approved:true, actual:7500, payment:'Transfer'},
        lineItems:[{label:'Wall socket + wiring', amount:6000},{label:'Callout / transport', amount:1500}],
        costHistory:[],
        timeline:[
            {icon:'alert-circle', label:'Guest reports sparking socket outlet', time:'6:40 PM'},
            {icon:'file-text', label:'Issue logged, room vacated as precaution', time:'6:42 PM'},
            {icon:'phone-call', label:'Called Chukwu Electricals', time:'6:55 PM'},
            {icon:'hammer', label:'Outlet and wiring replaced', time:'8:10 PM'},
            {icon:'check-circle-2', label:'Room returned to service', time:'8:30 PM'},
        ],
        attachments:[{type:'photo', name:'socket_before.jpg'},{type:'receipt', name:'receipt_401.jpg'}], repeatHistory:[],
        asset:{name:'Wall Socket Outlet', installed:'2020', warranty:'Expired', estReplacement:15000},
        cleaningAsked:true, needsCleaning:false },

    { id:IID++, room:'Room 208', area:'Rooms', category:'Water Heater', title:'Water heater tripping breaker', priority:'medium', status:'parts',
        reportedBy:'Housekeeping', reportedRel:'4 hrs ago', reportedAt:'Today, 11:30 AM', roomBlocked:true, blockDecided:true,
        vendorKey:'tunde', preferred:'WhatsApp', etaText:'Awaiting heating element',
        partsNeeded:'a replacement heating element',
        commLog:[{type:'call', note:'Called Tunde — confirmed heating element has failed again', time:'11:50 AM'},{type:'whatsapp', note:'Part ordered — 2 day wait for delivery', time:'12:05 PM'}],
        cost:{estimate:14000, approved:true, actual:null, payment:null},
        lineItems:[{label:'Heating element (4th replacement)', amount:9500},{label:'Callout / transport', amount:4500}],
        costHistory:[{when:'January', amount:11000, note:'Heating element replaced'},{when:'March', amount:13500, note:'Heating element replaced'},{when:'May', amount:12000, note:'Heating element + thermostat'}],
        timeline:[
            {icon:'alert-circle', label:'Housekeeping reports breaker tripping', time:'11:30 AM'},
            {icon:'file-text', label:'Issue logged', time:'11:32 AM'},
            {icon:'phone-call', label:'Called Tunde — diagnosed failed element', time:'11:50 AM'},
            {icon:'package', label:'Part ordered, 2 day wait', time:'12:05 PM'},
        ],
        attachments:[{type:'photo', name:'heater_208.jpg'}],
        repeatHistory:[{label:'Water Heater — element failed', when:'January'},{label:'Water Heater — element failed', when:'March'},{label:'Water Heater — element + thermostat', when:'May'},{label:'Water Heater — tripping breaker', when:'Now'}],
        asset:{name:'Ariston 30L Heater', installed:'2019', warranty:'Expired', estReplacement:95000},
        cleaningAsked:false, needsCleaning:null },
];

